import googleData from "@/data/google-reviews.json";
import manualData from "@/data/manual-reviews.json";

/**
 * Single source of truth for customer reviews.
 *
 * `google-reviews.json` is generated by `npm run fetch-reviews`, which pulls
 * the full Google Business Profile listing through SerpApi and downloads every
 * avatar and customer photo into `public/assets/reviews/`. Google revokes its
 * `lh3.googleusercontent.com` review-image tokens after a few days, so the JSON
 * stores local paths and never a Google URL.
 *
 * `manual-reviews.json` holds the hand-entered reviews that the Google fetch
 * cannot see: Yelp reviews, plus a few older Google ones no longer on the
 * listing. Re-running the fetch never touches that file.
 */

export type ReviewPhoto = { src: string; caption: string };

export type Review = {
  name: string;
  avatar: string | null;
  isLocalGuide: boolean;
  reviewCount: number | null;
  rating: number;
  text: string;
  ago: string;
  isoDate: string | null;
  photos: ReviewPhoto[];
  source: "google" | "yelp";
};

const google = googleData.reviews as Review[];
const manual = manualData.reviews as Review[];

/**
 * Google hands back relative dates ("5 months ago") which freeze at fetch time
 * and drift wrong between runs. An absolute month stays true until re-fetched.
 */
export function displayDate(review: Review): string {
  if (!review.isoDate) return review.ago;
  const d = new Date(review.isoDate);
  if (Number.isNaN(d.getTime())) return review.ago;
  return d.toLocaleDateString("en-US", { month: "long", year: "numeric", timeZone: "UTC" });
}

/** Reviews with no written text are real ratings but make empty cards. */
const hasText = (r: Review) => r.text.trim().length > 0;

function byPhotosThenDate(a: Review, b: Review) {
  if (a.photos.length !== b.photos.length) return b.photos.length - a.photos.length;
  if (a.isoDate && b.isoDate) return Date.parse(b.isoDate) - Date.parse(a.isoDate);
  return 0;
}

/** Every displayable review, photo-carrying ones first, then newest. */
export const REVIEWS: Review[] = [...google, ...manual].filter(hasText).sort(byPhotosThenDate);

/** Google's own review count, including star-only ratings with no text. */
export const GOOGLE_REVIEW_COUNT = google.length;

/** Total across every source, counting the star-only Google ratings. */
export const TOTAL_REVIEW_COUNT = google.length + manual.length;

export const AVERAGE_RATING =
  Math.round(
    ([...google, ...manual].reduce((sum, r) => sum + r.rating, 0) /
      (google.length + manual.length)) *
      10,
  ) / 10;

export const FIVE_STAR_PERCENT = Math.round(
  ([...google, ...manual].filter((r) => r.rating === 5).length /
    (google.length + manual.length)) *
    100,
);

/** Reviews that carry customer photos, for the homepage and gallery strips. */
export const REVIEWS_WITH_PHOTOS: Review[] = REVIEWS.filter((r) => r.photos.length > 0);

export const REVIEWS_FETCHED_AT: string = googleData.fetchedAt;
